create table if not exists bronze.avance_raw (
    id bigserial primary key,
    id_actualizacion text unique,
    semana int,
    anio int,
    semanas text,
    mes text,
    fecha date,
    cuadrilla text,
    zona text,
    nivel int,
    tipo_labor text,
    labor text,
    guardia text,
    turno text,
    jefe_guardia text,
    sup_tecnico text,
    supervisor_tecnico text,
    op_jumbo text,
    operador_jumbo text,
    avance numeric,
    ancho_proyectado numeric,
    alto_proyectado numeric,
    ancho_real numeric,
    alto_real numeric,
    tipo_voladura text,
    volumen_aparente numeric,
    volumen_medido numeric,
    numero_taladros int,
    longitud_perforacion numeric,
    senatel_pulsar_kg numeric,
    senatel_magnafrac_kg numeric,
    anfo_kg numeric,
    ingested_at timestamptz default now()
);
